[project]
name = "llm-bedrock-nova"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.92",
    "pillow>=11.1.0",
]

[project.entry-points.llm]
bedrock-nova = "llm_bedrock_nova"
